### ISSUE TITLE
Installing Issue on Python 2.7.9

### ISSUE THREAD

**Issue by belasin** [djedproject/djed.static#3]
pip install djed.static

Downloading/unpacking djed.static
  Downloading djed.static-0.5.tar.gz (881kB): 881kB downloaded
  Running setup.py egg_info for package djed.static
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/junwin/Documents/workspace/lm-calmsn/build/djed.static/setup.py", line 16, in <module>
        long_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
      File "/Users/junwin/Documents/workspace/lm-calmsn/build/djed.static/setup.py", line 8, in read
        return open(os.path.join(here, f), encoding='utf-8').read().strip()
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/junwin/Documents/workspace/lm-calmsn/build/djed.static/setup.py", line 16, in <module>

```
long_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
```

  File "/Users/junwin/Documents/workspace/lm-calmsn/build/djed.static/setup.py", line 8, in read

```
return open(os.path.join(here, f), encoding='utf-8').read().strip()
```

TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by belasin** [comment]
Created a pull request #4
